### ISSUE TITLE
Lỗi tạo product - Huy

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#19]
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/f8bfe267-963a-4ab1-a312-5eb4d1a2261f)

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/0f4083bf-081a-47c5-a388-e7aa22d9faf7)
Đã fix
