### ISSUE TITLE
Làm nổi bật tiêu đề - Minh

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#20]
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/ef669ef9-18b2-4d6c-a248-950947b6c78d)

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/3fb00e06-5f3e-4b6b-87c1-82fa9ff4bba7)
Đã fix
