### ISSUE TITLE
fix thiếu tiêu đề - Lâm

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#22]
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/05bb2f43-019e-478c-bc04-4c78a1ee9249)

**Comment by DuskLmao** [comment]
fixxed

**Comment by nxhdev2002** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/fc9030e6-41ed-4914-a8a2-62b3e8be6271)

Truyền title từ controller ra

**Comment by DuskLmao** [comment]
done
