### ISSUE TITLE
chỉnh sửa thông số ở trang chủ - Minh

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#23]
<img width="1309" alt="image" src="https://github.com/nxhdev2002/shop5cam/assets/22050271/2170410c-bbd0-4523-821c-6de0b878a895">

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/40e2815a-c794-417a-8980-f575542e951e)
Đã fix
