### ISSUE TITLE
Lỗi sản phẩm cuả tôi. - Huy

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#25]
<img width="1340" alt="image" src="https://github.com/nxhdev2002/shop5cam/assets/22050271/3b72b6d5-9d2f-40e3-9e94-04dcc57d1c5b">

**Comment by nxhdev2002** [comment]
Property [status] does not exist on this collection instance. (View: /Users/hoang0212/DEV/PHP/shop5cam/resources/views/seller/frontend/myproduct/index.blade.php)

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/ebfa46a0-1e6a-4cc5-83f4-b0108c409778)
Đã fix
