### ISSUE TITLE
Mất ảnh ở trang seller/products/my-product - Huy

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#26]
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/78e56e9a-243c-4831-ba9b-b641a43372dc)
 
Mất ảnh

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/493fda12-def9-42b2-bef8-8a707db3891e)
Đã fix
