### ISSUE TITLE
seller/products/my-product/edit/1

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#27]
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/b633b5f8-3793-4681-a58a-02a882a1a5b6)
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/44d8e891-f74a-4357-bfcc-0e85e0d77c0a)

Thiếu 1 trường thông tin ở trang sửa chi tiết sản phẩm + thiếu title

**Comment by DuskLmao** [comment]
fixxed title
