### ISSUE TITLE
Trang chủ

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#28]
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/f92d9818-bfbf-4148-a06c-0c9e94d950cc)

Sửa lại các tab services + faq

![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/34398af2-6759-4614-b604-2d45c1d96300)
Sửa lại Orders LastMonth thành Total Orders
Xoá trường 5 star thay bằng 1 trường khác (vì 5 star) không có ý nghĩa thống kê

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/fa8ddc02-17e1-49da-8505-48516673ed5d)
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/934a2a3f-218d-4888-973e-519b7ec6fd3b)
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/10d735bb-6b53-467a-a0ca-f29a68edafe8)
Update thêm services
