### ISSUE TITLE
seller/products/my-product

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#29]
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/d54e9a18-61cd-49f4-b1fc-a776801ed7ef)
Cho khoảng scroll dài  ra tí nữa + Làm nút xoá sản phẩm ( chỉ ẩn đi sản phẩm chứ k xoá khỏi database )

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/7ce66d3a-9850-4c76-b968-82b883374985)
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/3ec38fc8-c58f-46dd-bb6e-bd6568df7540)
Đã fix

**Comment by nxhdev2002** [comment]
ý là xoá luôn scroll đi 
![image](https://github.com/nxhdev2002/shop5cam/assets/22050271/3ba41bab-3275-4d34-a0ba-7c147e704706)

để scoll sẽ ảnh hưởng đến ux

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/b1142a0d-b751-4128-86f5-c28ad672b5d5)
Đã fix

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/94a715de-cdeb-4b70-a7fa-8d1a4f1e535e)

**Comment by nxhdev2002** [comment]
<img width="1076" alt="image" src="https://github.com/nxhdev2002/shop5cam/assets/22050271/cf9331fe-b8e6-495b-8f20-0684f5bef8b5">
khi bấm vào nút xoá làm thêm popup xác nhận xoá sản phẩm hay không

**Comment by quangwuy02** [comment]
![image](https://github.com/nxhdev2002/shop5cam/assets/121009933/00b52e80-160e-4075-bec6-69fc2f902bd8)
Như này đã được chưa hay là để tạo thêm cái modal ở giữa á
