### ISSUE TITLE
Phần lọc sản phẩm hiển thị cả các mặt hàng đã bị xoá

### ISSUE THREAD

**Issue by nxhdev2002** [nxhdev2002/shop5cam#31]
<img width="1137" alt="image" src="https://github.com/nxhdev2002/shop5cam/assets/22050271/4b150a35-5ea7-4806-b483-ce340bd016ef">
Phần lọc sản phẩm hiển thị cả các mặt hàng đã bị xoá

**Comment by quangwuy02** [comment]
đã fix
